In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
# Remove unwanted columns
df.drop(columns=['listed_in', 'description', 'cast'], inplace=True)

# Set index as show_id
df.set_index('show_id', inplace=True)
df.head()

,type,title,director,country,date_added,release_year,rating,duration
show_id,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,"September 25, 2021",2020,PG-13,90 min
s2,TV Show,Blood & Water,NaN,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
s3,TV Show,Ganglands,Julien Leclercq,NaN,"September 24, 2021",2021,TV-MA,1 Season
s4,TV Show,Jailbirds New Orleans,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season
s5,TV Show,Kota Factory,NaN,India,"September 24, 2021",2021,TV-MA,2 Seasons

In [3]:
# Find all Meta-Data of the Dataset

print(f'Rows : {df.shape[0]}, Columns : {df.shape[1]}')
print(f'Total Data : {df.size}')
print('\n\nInfo : \n')
df.info()

Rows : 8807, Columns : 8
Total Data : 70456


Info :

<class 'pandas.DataFrame'>
Index: 8807 entries, s1 to s8807
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8807 non-null   str
 1   title         8807 non-null   str
 2   director      6173 non-null   str
 3   country       7976 non-null   str
 4   date_added    8797 non-null   str
 5   release_year  8807 non-null   int64
 6   rating        8803 non-null   str
 7   duration      8804 non-null   str
dtypes: int64(1), str(7)
memory usage: 619.2+ KB

In [4]:
# All rows and columns
cols = df.columns.tolist()
idx = df.index.tolist()

print(f'\nColumn data : {cols}')

Column data : ['type', 'title', 'director', 'country', 'date_added', 'release_year', 'rating', 'duration']

In [5]:
df.head()

,type,title,director,country,date_added,release_year,rating,duration
show_id,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,"September 25, 2021",2020,PG-13,90 min
s2,TV Show,Blood & Water,NaN,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
s3,TV Show,Ganglands,Julien Leclercq,NaN,"September 24, 2021",2021,TV-MA,1 Season
s4,TV Show,Jailbirds New Orleans,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season
s5,TV Show,Kota Factory,NaN,India,"September 24, 2021",2021,TV-MA,2 Seasons

In [6]:
# Converting to Date-Time Datatype
df['date_added'] = pd.to_datetime(df['date_added'], format = 'mixed')
df.head()

,type,title,director,country,date_added,release_year,rating,duration
show_id,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min
s2,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,TV-MA,2 Seasons
s3,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,TV-MA,1 Season
s4,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,TV-MA,1 Season
s5,TV Show,Kota Factory,NaN,India,2021-09-24,2021,TV-MA,2 Seasons

In [7]:
df = df[['title', 'type', 'country', 'release_year', 'director', 'rating', 'duration', 'date_added']]
df.head()

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s1,Dick Johnson Is Dead,Movie,United States,2020,Kirsten Johnson,PG-13,90 min,2021-09-25
s2,Blood & Water,TV Show,South Africa,2021,NaN,TV-MA,2 Seasons,2021-09-24
s3,Ganglands,TV Show,NaN,2021,Julien Leclercq,TV-MA,1 Season,2021-09-24
s4,Jailbirds New Orleans,TV Show,NaN,2021,NaN,TV-MA,1 Season,2021-09-24
s5,Kota Factory,TV Show,India,2021,NaN,TV-MA,2 Seasons,2021-09-24

In [8]:
# Find unique values in each column
udf = df.nunique().to_frame('Number of Unique elements').sort_values(by = 'Number of Unique elements')
udf

              Number of Unique elements
type                                  2
rating                               17
release_year                         74
duration                            220
country                             748
date_added                         1714
director                           4528
title                              8807

In [9]:
df.sample(5) # Randomly selects any 5 tuples

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s6545,Cult of Chucky,Movie,United States,2017,Don Mancini,R,90 min,2017-10-03
s2484,Fifty Year Old Teenager,Movie,NaN,1996,Fouad Al Shatti,TV-14,204 min,2020-05-21
s3218,The Island,Movie,Nigeria,2018,Toka McBaror,TV-14,93 min,2019-11-29
s5276,Heroin(e),Movie,United States,2017,Elaine McMillion Sheldon,TV-14,40 min,2017-09-12
s5838,X: Past Is Present,Movie,India,2015,"Hemant Gaba, Pratim D. Gupta, Sudhish Kamath, ...",TV-MA,105 min,2016-07-01

In [10]:
# Finding number of movies and number of TV shows
print('Number of movies : ', len(df[df['type'] == 'Movie']))
print('Number of TV shows : ', len(df[df['type'] == 'TV Show']))

Number of movies :  6131
Number of TV shows :  2676

In [11]:
# Oldest title in the dataset
df[df['date_added'] == df['date_added'].min()]['title']

show_id
s5958    To and From New York
Name: title, dtype: str

In [12]:
# Newest title in the dataset
df[df['date_added'] == df['date_added'].max()]['title']

show_id
s1    Dick Johnson Is Dead
Name: title, dtype: str

In [13]:
# Unique countries
df['country'].nunique()

748

In [14]:
# Removed NaN country values
newdf = df['country'].dropna()
newdf.head()

show_id
s1                                        United States
s2                                         South Africa
s5                                                India
s8    United States, Ghana, Burkina Faso, United Kin...
s9                                       United Kingdom
Name: country, dtype: str

In [15]:
# Splitting countries as array of different countries
newdf = newdf.str.split(',')

In [16]:
# Exploding many values into many rows
newdf = newdf.explode()
newdf.head(15)

show_id
s1       United States
s2        South Africa
s5               India
s8       United States
s8               Ghana
s8        Burkina Faso
s8      United Kingdom
s8             Germany
s8            Ethiopia
s9      United Kingdom
s10      United States
s13            Germany
s13     Czech Republic
s16      United States
s18             Mexico
Name: country, dtype: str

In [17]:
# Finding value counts
newdf = newdf.str.strip()
newdf.value_counts()

country
United States     3690
India             1046
United Kingdom     806
Canada             445
France             393
                  ...
Sudan                1
Panama               1
Uganda               1
East Germany         1
Montenegro           1
Name: count, Length: 123, dtype: int64

In [18]:
# Finding country with maximum titles
newdf.value_counts().iloc[:1]

country
United States    3690
Name: count, dtype: int64

In [19]:
# How many titles added in the year 2020
len(df[df['date_added'].dt.year == 2020])

1879

In [20]:
# All movies released after 2018
df[df['release_year'] >= 2018].sort_values(by='release_year').head(10)

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s8649,Two Graves,Movie,United Kingdom,2018,Gary Young,TV-MA,80 min,2019-05-01
s8647,Twirlywoos,TV Show,United Kingdom,2018,NaN,TV-Y,2 Seasons,2020-05-15
s8646,Twinsanity,Movie,United States,2018,Buz Wallick,TV-MA,86 min,2019-03-15
s8596,Tinker',Movie,United States,2018,Sonny Marler,TV-14,97 min,2019-03-19
s8566,The World's Most Wanted Animal,Movie,United Kingdom,2018,Victoria Bromley,TV-PG,53 min,2019-04-01
s8560,The Witch Files,Movie,United States,2018,Kyle Rankin,TV-14,88 min,2019-02-01
s8525,The Surrounding Game,Movie,United States,2018,"Will Lockhart, Cole D. Pruitt",TV-14,98 min,2018-08-30
s8471,The Push,Movie,United States,2018,"Grant Korgan, Brian Niles",TV-MA,90 min,2019-06-07
s8451,The Perfect Day,Movie,NaN,2018,Jean-Pierre Devillers,TV-14,93 min,2018-09-01
s8442,The Nutcracker and the Four Realms,Movie,United States,2018,"Lasse Hallström, Joe Johnston",PG,99 min,2019-05-28

In [21]:
# Find every TV show with more than 3 seasons
df['duration'].value_counts() # Hence empty answer

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
             ...
228 min         1
18 min          1
205 min         1
201 min         1
191 min         1
Name: count, Length: 220, dtype: int64

In [22]:
# Splitting director column
dcol = df['director'].copy()
dcol = dcol.str.split(',')
dcol.dropna(inplace = True) # remove NaN values
dcol.head(10)

show_id
s1                    [Kirsten Johnson]
s3                    [Julien Leclercq]
s6                      [Mike Flanagan]
s7     [Robert Cullen,  José Luis Ucha]
s8                       [Haile Gerima]
s9                    [Andy Devonshire]
s10                    [Theodore Melfi]
s12                 [Kongkiat Komesiri]
s13               [Christian Schwochow]
s14                     [Bruno Garotti]
Name: director, dtype: object

In [23]:
# Explode director column
dcol = dcol.explode()
dcol = dcol.str.strip()
dcol.head(20)

show_id
s1            Kirsten Johnson
s3            Julien Leclercq
s6              Mike Flanagan
s7              Robert Cullen
s7             José Luis Ucha
s8               Haile Gerima
s9            Andy Devonshire
s10            Theodore Melfi
s12         Kongkiat Komesiri
s13       Christian Schwochow
s14             Bruno Garotti
s17    Pedro de Echave García
s17     Pablo Azorín Williams
s19                Adam Salky
s21           Olivier Megaton
s23            K.S. Ravikumar
s24                  Alex Woo
s24             Stanley Moore
s25                S. Shankar
s27               Rajiv Menon
Name: director, dtype: str

In [24]:
# Find top 10 directors with highest number of titles
dcol.value_counts().iloc[:10]

director
Rajiv Chilaka          22
Jan Suter              21
Raúl Campos            19
Suhas Kadav            16
Marcus Raboy           16
Jay Karas              15
Cathy Garcia-Molina    13
Youssef Chahine        12
Martin Scorsese        12
Jay Chapman            12
Name: count, dtype: int64

In [25]:
# Which rating appears most frequently
df['rating'].value_counts().iloc[:1]

rating
TV-MA    3207
Name: count, dtype: int64

In [26]:
# Which release year has maximum number of titles
df['release_year'].value_counts().iloc[:1]

release_year
2018    1147
Name: count, dtype: int64

In [27]:
# Find all indian movies
# Sorted by increasing order of release_year
df[df['country'] == 'India'].head(10).sort_values(by='release_year')

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s115,Anjaam,Movie,India,1994,Rahul Rawail,TV-14,143 min,2021-09-02
s25,Jeans,Movie,India,1998,S. Shankar,TV-14,166 min,2021-09-21
s67,Raja Rasoi Aur Anya Kahaniyan,TV Show,India,2014,NaN,TV-G,1 Season,2021-09-15
s51,Dharmakshetra,TV Show,India,2014,NaN,TV-PG,1 Season,2021-09-15
s70,Stories by Rabindranath Tagore,TV Show,India,2015,NaN,TV-PG,1 Season,2021-09-15
s117,Dhanak,Movie,India,2015,Nagesh Kukunoor,TV-PG,114 min,2021-09-02
s119,Gurgaon,Movie,India,2017,Shanker Raman,TV-14,106 min,2021-09-02
s106,Angamaly Diaries,Movie,India,2017,Lijo Jose Pellissery,TV-14,128 min,2021-09-05
s5,Kota Factory,TV Show,India,2021,NaN,TV-MA,2 Seasons,2021-09-24
s40,Chhota Bheem,TV Show,India,2021,NaN,TV-Y7,3 Seasons,2021-09-16

In [28]:
# Find all titles which have no director listed
df[df['director'].isna() == True]['title'].head(10)

show_id
s2                           Blood & Water
s4                   Jailbirds New Orleans
s5                            Kota Factory
s11    Vendetta: Truth, Lies and The Mafia
s15        Crime Stories: India Detectives
s16                      Dear White People
s18                        Falsa identidad
s20                                 Jaguar
s22                 Resurrection: Ertugrul
s26                   Love on the Spectrum
Name: title, dtype: str

In [29]:
# How many rows contain missing values
df[df.isna().any(axis=1)] # To find all rows having missing values

df.isna().any(axis=1).sum() # To find total no. of rows having missing values

np.int64(3060)

In [30]:
# Find % of missing values in every column
tot = len(df)
perc = {}

for ele in cols:
    perc[ele] = (df[ele].isna().sum() / tot * 100).round(2)

pd.Series(perc)

type             0.00
title            0.00
director        29.91
country          9.44
date_added       0.11
release_year     0.00
rating           0.05
duration         0.03
dtype: float64

In [31]:
# Grouping data based on type
df[['type','rating']].groupby('type').value_counts()

type     rating
Movie    TV-MA       2062
         TV-14       1427
         R            797
         TV-PG        540
         PG-13        490
         PG           287
         TV-Y7        139
         TV-Y         131
         TV-G         126
         NR            75
         G             41
         TV-Y7-FV       5
         UR             3
         NC-17          3
         84 min         1
         66 min         1
         74 min         1
TV Show  TV-MA       1145
         TV-14        733
         TV-PG        323
         TV-Y7        195
         TV-Y         176
         TV-G          94
         NR             5
         R              2
         TV-Y7-FV       1
Name: count, dtype: int64

In [32]:
# Among movies, which rating is most common
df[['type','rating']].groupby('type').value_counts().loc['Movie'][:1]

rating
TV-MA    2062
Name: count, dtype: int64

In [33]:
# Among TV Shows, which country produces most content
df[['type','country']].groupby('type').value_counts() # Countries not splitted

type     country
Movie    United States                                                                         2058
         India                                                                                  893
         United Kingdom                                                                         206
         Canada                                                                                 122
         Spain                                                                                   97
                                                                                               ...
TV Show  Senegal                                                                                  1
         United States, Hungary, Ireland, Canada                                                  1
         United Kingdom, Finland, Germany, United States, Australia, Japan, France, Ireland       1
         Norway, United States                                                                    1
         Germany, Australia, France, China                                                        1
Name: count, Length: 847, dtype: int64

In [34]:
# Creating a new df
csdf = df[['type','country']].copy()
csdf.sample(10)

            type                country
show_id
s7590    TV Show  Canada, United States
s4114      Movie                  Spain
s2990      Movie                 Taiwan
s4809      Movie                  Chile
s8710      Movie                 Poland
s6625      Movie          United States
s6911      Movie   United States, Japan
s5151    TV Show         United Kingdom
s2589    TV Show                 Canada
s7878      Movie         United Kingdom

In [35]:
# Splitting countries
csdf['country'] = csdf['country'].str.split(',')
csdf.sample(10)

            type                                            country
show_id
s8505      Movie                                            [India]
s2465      Movie                             [United Arab Emirates]
s3704      Movie                 [Colombia,  Peru,  United Kingdom]
s4179    TV Show                                    [United States]
s386     TV Show                                          [Germany]
s2556      Movie                             [United Arab Emirates]
s4677    TV Show  [United States,  Brazil,  South Korea,  Mexico...
s2119    TV Show                                    [United States]
s542       Movie                                            [India]
s2409    TV Show                                      [South Korea]

In [36]:
# Exploding values
csdf = csdf.explode('country')
csdf.sample(10)

            type        country
show_id
s5868    TV Show  United States
s425       Movie            NaN
s5247    TV Show      Singapore
s7224      Movie        Germany
s58        Movie          Japan
s836     TV Show            NaN
s6494      Movie  United States
s1625      Movie         France
s5061      Movie      Singapore
s5158    TV Show    South Korea

In [37]:
# Removing whitespace 
csdf['country'] = csdf['country'].str.strip()

# Among TV Shows, which country produces most content
res = csdf.groupby('type').value_counts()
res

# Answer -> For TV Show, each country produces only one TV Show, hence no comparision

type     country
Movie    United States     2752
         India              962
         United Kingdom     534
         Canada             319
         France             303
                           ...
TV Show  Austria              1
         Malta                1
         Belarus              1
         Senegal              1
         Puerto Rico          1
Name: count, Length: 184, dtype: int64

In [38]:
# Which month netflix has added highest number of titles - July
df['date_added'].dt.month_name().value_counts()[:1]

date_added
July    827
Name: count, dtype: int64

In [39]:
# Which year netflix has added highest number of titles - 2019
df['date_added'].dt.year.value_counts()[:1]

date_added
2019.0    2016
Name: count, dtype: int64

In [40]:
# Which decade produced max content
# Let's create a new table
dec = df['release_year'].copy().to_frame()

# Function to Calculate Decade
def to_decade(year):
    syear = str(year)
    return(int(syear[:3] + '0'))

dec['decade'] = dec['release_year'].apply(to_decade)
dec.tail()

         release_year  decade
show_id
s8803            2007    2000
s8804            2018    2010
s8805            2009    2000
s8806            2006    2000
s8807            2015    2010

In [41]:
# Find answer - 2010s produced maximum content
dec[['decade']].groupby('decade').value_counts().sort_values().iloc[-1:]

decade
2010    5927
Name: count, dtype: int64

In [42]:
# Find director who has directed both Movies and TV Shows

# First create a separate df
ddf = df[['type', 'director']].copy()
ddf.dropna(subset=['director'], inplace=True)
ddf.head(15)

            type                                       director
show_id
s1         Movie                                Kirsten Johnson
s3       TV Show                                Julien Leclercq
s6       TV Show                                  Mike Flanagan
s7         Movie                  Robert Cullen, José Luis Ucha
s8         Movie                                   Haile Gerima
s9       TV Show                                Andy Devonshire
s10        Movie                                 Theodore Melfi
s12      TV Show                              Kongkiat Komesiri
s13        Movie                            Christian Schwochow
s14        Movie                                  Bruno Garotti
s17        Movie  Pedro de Echave García, Pablo Azorín Williams
s19        Movie                                     Adam Salky
s21      TV Show                                Olivier Megaton
s23        Movie                                 K.S. Ravikumar
s24        Movie                        Alex Woo, Stanley Moore

In [43]:
# We need to separate Director Names
ddf['director'] = ddf['director'].str.split(',')
ddf.head(15)

            type                                          director
show_id
s1         Movie                                 [Kirsten Johnson]
s3       TV Show                                 [Julien Leclercq]
s6       TV Show                                   [Mike Flanagan]
s7         Movie                  [Robert Cullen,  José Luis Ucha]
s8         Movie                                    [Haile Gerima]
s9       TV Show                                 [Andy Devonshire]
s10        Movie                                  [Theodore Melfi]
s12      TV Show                               [Kongkiat Komesiri]
s13        Movie                             [Christian Schwochow]
s14        Movie                                   [Bruno Garotti]
s17        Movie  [Pedro de Echave García,  Pablo Azorín Williams]
s19        Movie                                      [Adam Salky]
s21      TV Show                                 [Olivier Megaton]
s23        Movie                                  [K.S. Ravikumar]
s24        Movie                        [Alex Woo,  Stanley Moore]

In [44]:
# Explode the Director Names and Remove Whitespace
ddf = ddf.explode('director')
ddf['director'] = ddf['director'].str.strip()
ddf.head(20)

            type                director
show_id
s1         Movie         Kirsten Johnson
s3       TV Show         Julien Leclercq
s6       TV Show           Mike Flanagan
s7         Movie           Robert Cullen
s7         Movie          José Luis Ucha
s8         Movie            Haile Gerima
s9       TV Show         Andy Devonshire
s10        Movie          Theodore Melfi
s12      TV Show       Kongkiat Komesiri
s13        Movie     Christian Schwochow
s14        Movie           Bruno Garotti
s17        Movie  Pedro de Echave García
s17        Movie   Pablo Azorín Williams
s19        Movie              Adam Salky
s21      TV Show         Olivier Megaton
s23        Movie          K.S. Ravikumar
s24        Movie                Alex Woo
s24        Movie           Stanley Moore
s25        Movie              S. Shankar
s27        Movie             Rajiv Menon

In [45]:
# People who have directed both movies and TV shows

dirs = ddf.groupby('director')['type'].nunique()
dirs[dirs == 2].to_frame()

                      type
director
Abhishek Chaubey         2
Alastair Fothergill      2
Alban Teurlai            2
Alessandro Angulo        2
Andrew Tan               2
...                    ...
Tsutomu Mizushima        2
Vasan Bala               2
Vikramaditya Motwane     2
Weica Wang               2
Ziad Doueiri             2

[83 rows x 1 columns]

In [46]:
ddf[ddf['director'] == 'Alban Teurlai']

            type       director
show_id
s1801    TV Show  Alban Teurlai
s5309      Movie  Alban Teurlai

In [47]:
# Find the country whose average release year is the highest

# Create a new df
cdf = df[['country', 'release_year']].copy()
cdf.dropna(inplace=True)
cdf.head()

                                                   country  release_year
show_id
s1                                           United States          2020
s2                                            South Africa          2021
s5                                                   India          2021
s8       United States, Ghana, Burkina Faso, United Kin...          1993
s9                                          United Kingdom          2021

In [48]:
# Split Country
cdf['country'] = cdf['country'].str.split(',')
cdf.head()

                                                   country  release_year
show_id
s1                                         [United States]          2020
s2                                          [South Africa]          2021
s5                                                 [India]          2021
s8       [United States,  Ghana,  Burkina Faso,  United...          1993
s9                                        [United Kingdom]          2021

In [49]:
# Explode Country
cdf = cdf.explode('country')
cdf['country'] = cdf['country'].str.strip()
cdf.head(15)

                country  release_year
show_id
s1        United States          2020
s2         South Africa          2021
s5                India          2021
s8        United States          1993
s8                Ghana          1993
s8         Burkina Faso          1993
s8       United Kingdom          1993
s8              Germany          1993
s8             Ethiopia          1993
s9       United Kingdom          2021
s10       United States          2021
s13             Germany          2021
s13      Czech Republic          2021
s16       United States          2021
s18              Mexico          2020

In [50]:
# Using groupby to find answers
netyears = len(cdf)

res = cdf.groupby('country').size().to_frame('Average years')
res['Average years'] = (res['Average years'] / netyears).round(2)
res = res.sort_values(by='Average years', ascending=False)
res

# United States is the country with highest average release years

                Average years
country
United States            0.37
India                    0.10
United Kingdom           0.08
France                   0.04
Canada                   0.04
...                       ...
Vatican City             0.00
Venezuela                0.00
Vietnam                  0.00
West Germany             0.00
Zimbabwe                 0.00

[123 rows x 1 columns]

In [51]:
# Among titles added in 2021, which rating appears most often?

# Create a separate df
rdf = df['rating'].to_frame()
rdf['year_added'] = df['date_added'].dt.year
rdf.dropna(inplace=True)
rdf['year_added'] = rdf['year_added'].astype(int)
rdf.tail(10)

        rating  year_added
show_id
s8798    TV-Y7        2018
s8799    TV-MA        2019
s8800    TV-14        2018
s8801    TV-PG        2016
s8802    TV-MA        2016
s8803        R        2019
s8804    TV-Y7        2019
s8805        R        2019
s8806       PG        2020
s8807    TV-14        2019

In [52]:
# Keep only values where year_added == 2021
rdf = rdf[ rdf['year_added'] == 2021 ]
rdf.head(20)
#len(rdf)

        rating  year_added
show_id
s1       PG-13        2021
s2       TV-MA        2021
s3       TV-MA        2021
s4       TV-MA        2021
s5       TV-MA        2021
s6       TV-MA        2021
s7          PG        2021
s8       TV-MA        2021
s9       TV-14        2021
s10      PG-13        2021
s11      TV-MA        2021
s12      TV-MA        2021
s13      TV-MA        2021
s14      TV-PG        2021
s15      TV-MA        2021
s16      TV-MA        2021
s17      TV-MA        2021
s18      TV-MA        2021
s19      TV-14        2021
s20      TV-MA        2021

In [53]:
# Use Group-By to find answers
res = rdf.groupby('rating').size().to_frame('Freq')
res = res.sort_values(by='Freq', ascending=False)
res

# Among titles added in 2021, "TV-MA" rating appears most often

        Freq
rating
TV-MA    489
TV-14    326
R        190
PG-13    146
TV-PG     97
TV-Y7     87
PG        58
TV-Y      57
TV-G      44
G          4

In [54]:
# Find the longest movie

# Create a new df
mdf = df[df['type'] == 'Movie']
mdf.dropna(inplace=True) # Remove NaN values
mdf.head()

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s1,Dick Johnson Is Dead,Movie,United States,2020,Kirsten Johnson,PG-13,90 min,2021-09-25
s8,Sankofa,Movie,"United States, Ghana, Burkina Faso, United Kin...",1993,Haile Gerima,TV-MA,125 min,2021-09-24
s10,The Starling,Movie,United States,2021,Theodore Melfi,PG-13,104 min,2021-09-24
s13,Je Suis Karl,Movie,"Germany, Czech Republic",2021,Christian Schwochow,TV-MA,127 min,2021-09-23
s25,Jeans,Movie,India,1998,S. Shankar,TV-14,166 min,2021-09-21

In [55]:
# Manipulate duration column to make it int type

# Create a function
def change(dur):
    res = dur.split(' ')[0]
    return res

# Apply the function
mdf['duration'] = mdf['duration'].apply(change)

# Now change the datatype of duration to int
mdf['duration'] = mdf['duration'].astype(int)

# Sort in descending order
mdf = mdf.sort_values(by='duration', ascending=False)
mdf.head()

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s2492,The School of Mischief,Movie,Egypt,1973,Houssam El-Din Mustafa,TV-14,253,2020-05-21
s2488,No Longer kids,Movie,Egypt,1979,Samir Al Asfory,TV-14,237,2020-05-21
s167,Once Upon a Time in America,Movie,"Italy, United States",1984,Sergio Leone,R,229,2021-09-01
s7933,Sangam,Movie,India,1964,Raj Kapoor,TV-14,228,2019-12-31
s1020,Lagaan,Movie,"India, United Kingdom",2001,Ashutosh Gowariker,PG,224,2021-04-17

In [56]:
# Find the answer
mdf[mdf['duration'] == mdf['duration'].max()]

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s2492,The School of Mischief,Movie,Egypt,1973,Houssam El-Din Mustafa,TV-14,253,2020-05-21

In [57]:
'''
Create a DataFrame that contains only:

Country
Number of Movies
Number of TV Shows
Total Titles

sorted by Total Titles
'''

# Create a new df
sol = df[['type', 'country']]
sol = sol.dropna()
sol.head()

            type                                            country
show_id
s1         Movie                                      United States
s2       TV Show                                       South Africa
s5       TV Show                                              India
s8         Movie  United States, Ghana, Burkina Faso, United Kin...
s9       TV Show                                     United Kingdom

In [58]:
# Country needs to be split
sol['country'] = sol['country'].str.split(',')
sol.head()

            type                                            country
show_id
s1         Movie                                    [United States]
s2       TV Show                                     [South Africa]
s5       TV Show                                            [India]
s8         Movie  [United States,  Ghana,  Burkina Faso,  United...
s9       TV Show                                   [United Kingdom]

In [60]:
# Explode Country
sol = sol.explode('country')

# Remove whitespace
sol['country'] = sol['country'].str.strip()
sol = sol[sol['country'] != ' ']
sol.head()

            type        country
show_id
s1         Movie  United States
s2       TV Show   South Africa
s5       TV Show          India
s8         Movie  United States
s8         Movie          Ghana

In [61]:
canal = sol.groupby('country').size().to_frame('Titles')
canal = canal.sort_values(by='Titles')
canal.head()

             Titles
country
Afghanistan       1
Albania           1
Armenia           1
Angola            1
Belarus           1

In [62]:
# Movie Analysis
mov = sol[sol['type'] == 'Movie']
mov.head()

          type         country
show_id
s1       Movie   United States
s8       Movie   United States
s8       Movie           Ghana
s8       Movie    Burkina Faso
s8       Movie  United Kingdom

In [63]:
# Group-By Movies
manal = mov.groupby('country').size().to_frame('Movies')
manal.head()

             Movies
country
                  6
Afghanistan       1
Albania           1
Algeria           3
Angola            1