In [164]:
import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [165]:
# Remove unwanted columns
df.drop(columns=['listed_in', 'description', 'cast'], inplace=True)

# Set index as show_id
df.set_index('show_id', inplace=True)
df.head()

,type,title,director,country,date_added,release_year,rating,duration
show_id,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,"September 25, 2021",2020,PG-13,90 min
s2,TV Show,Blood & Water,NaN,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
s3,TV Show,Ganglands,Julien Leclercq,NaN,"September 24, 2021",2021,TV-MA,1 Season
s4,TV Show,Jailbirds New Orleans,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season
s5,TV Show,Kota Factory,NaN,India,"September 24, 2021",2021,TV-MA,2 Seasons

In [166]:
# Find all Meta-Data of the Dataset

print(f'Rows : {df.shape[0]}, Columns : {df.shape[1]}')
print(f'Total Data : {df.size}')
print('\n\nInfo : \n')
df.info()

Rows : 8807, Columns : 8
Total Data : 70456


Info :

<class 'pandas.DataFrame'>
Index: 8807 entries, s1 to s8807
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8807 non-null   str
 1   title         8807 non-null   str
 2   director      6173 non-null   str
 3   country       7976 non-null   str
 4   date_added    8797 non-null   str
 5   release_year  8807 non-null   int64
 6   rating        8803 non-null   str
 7   duration      8804 non-null   str
dtypes: int64(1), str(7)
memory usage: 619.2+ KB

In [167]:
# All rows and columns
cols = df.columns.tolist()
idx = df.index.tolist()

print(f'\nColumn data : {cols}')

Column data : ['type', 'title', 'director', 'country', 'date_added', 'release_year', 'rating', 'duration']

In [168]:
df.head()

,type,title,director,country,date_added,release_year,rating,duration
show_id,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,"September 25, 2021",2020,PG-13,90 min
s2,TV Show,Blood & Water,NaN,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
s3,TV Show,Ganglands,Julien Leclercq,NaN,"September 24, 2021",2021,TV-MA,1 Season
s4,TV Show,Jailbirds New Orleans,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season
s5,TV Show,Kota Factory,NaN,India,"September 24, 2021",2021,TV-MA,2 Seasons

In [169]:
# Converting to Date-Time Datatype
df['date_added'] = pd.to_datetime(df['date_added'], format = 'mixed')
df.head()

,type,title,director,country,date_added,release_year,rating,duration
show_id,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min
s2,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,TV-MA,2 Seasons
s3,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,TV-MA,1 Season
s4,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,TV-MA,1 Season
s5,TV Show,Kota Factory,NaN,India,2021-09-24,2021,TV-MA,2 Seasons

In [170]:
df = df[['title', 'type', 'country', 'release_year', 'director', 'rating', 'duration', 'date_added']]
df.head()

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s1,Dick Johnson Is Dead,Movie,United States,2020,Kirsten Johnson,PG-13,90 min,2021-09-25
s2,Blood & Water,TV Show,South Africa,2021,NaN,TV-MA,2 Seasons,2021-09-24
s3,Ganglands,TV Show,NaN,2021,Julien Leclercq,TV-MA,1 Season,2021-09-24
s4,Jailbirds New Orleans,TV Show,NaN,2021,NaN,TV-MA,1 Season,2021-09-24
s5,Kota Factory,TV Show,India,2021,NaN,TV-MA,2 Seasons,2021-09-24

In [178]:
# Find unique values in each column
udf = df.nunique().to_frame('Number of Unique elements').sort_values(by = 'Number of Unique elements')
udf

              Number of Unique elements
type                                  2
rating                               18
release_year                         74
duration                            221
country                             749
date_added                         1714
director                           4529
title                              8807

In [180]:
df.sample(5) # Randomly selects any 5 tuples

,title,type,country,release_year,director,rating,duration,date_added
show_id,,,,,,,,
s2664,Varane Avashyamund,Movie,India,2020,Anoop Sathyan,TV-14,144 min,2020-04-20
s787,Company of Heroes,Movie,United States,2013,Don Michael Paul,R,101 min,2021-06-02
s7676,Operation Proposal,TV Show,South Korea,2012,NF,TV-PG,1 Season,2016-07-01
s183,Welcome Home Roscoe Jenkins,Movie,United States,2008,Malcolm D. Lee,PG-13,114 min,2021-09-01
s4609,Three Wives One Husband,TV Show,United Kingdom,2018,NF,TV-14,1 Season,2018-10-01