## Exploratory Data Analysis of House Prices Dataset using Pandas Library in Python

In [3]:
import pandas as pd
df = pd.read_csv('house_prices.csv')
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768

## Initial Exploration of Dataset

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   street     985 non-null    str
 1   city       985 non-null    str
 2   zip        985 non-null    int64
 3   state      985 non-null    str
 4   beds       985 non-null    int64
 5   baths      985 non-null    int64
 6   sq__ft     985 non-null    int64
 7   type       985 non-null    str
 8   sale_date  985 non-null    str
 9   price      985 non-null    int64
 10  latitude   985 non-null    float64
 11  longitude  985 non-null    float64
dtypes: float64(2), int64(5), str(5)
memory usage: 92.5 KB

In [5]:
df.size

11820

In [6]:
df.describe().round(2).loc[['count', 'min', 'max', 'mean']]

           zip    beds   baths   sq__ft      price  latitude  longitude
count    985.0  985.00  985.00   985.00     985.00    985.00     985.00
min    95603.0    0.00    0.00     0.00    1551.00     38.24    -121.55
max    95864.0    8.00    5.00  5822.00  884790.00     39.02    -120.60
mean   95750.7    2.91    1.78  1314.92  234144.26     38.61    -121.36

In [7]:
df.nunique().to_frame('Number of Unique Values')

           Number of Unique Values
street                         981
city                            39
zip                             68
state                            1
beds                             8
baths                            6
sq__ft                         603
type                             4
sale_date                        5
price                          605
latitude                       969
longitude                      967

### Level - 1 Questions

#### 1) How many rows and cols?

In [8]:
print(f'Rows = {df.shape[0]}, Columns = {df.shape[1]}')

Rows = 985, Columns = 12

#### 2) Min, Max and Avg Prices of Houses?

In [9]:
print('Min : ', df['price'].min())
print('Max : ', df['price'].max())
print('Avg : ', df['price'].mean().round(2))

Min :  1551
Max :  884790
Avg :  234144.26

#### 3) Filter the dataframe to show only the houses located in the city of 'SACRAMENTO'. How many are there?

In [10]:
df[df['city'] == 'SACRAMENTO'].sample(5)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
915,5920 VALLEY GLEN WAY,SACRAMENTO,95823,CA,3,2,1265,Residential,2008-05-15,164000,38.462821,-121.433135
841,3108 DELWOOD WAY,SACRAMENTO,95821,CA,4,2,2053,Residential,2008-05-16,450000,38.621566,-121.370882
870,5672 HILLSDALE BLVD,SACRAMENTO,95842,CA,2,1,933,Condo,2008-05-15,62000,38.670467,-121.359799
251,8219 GWINHURST CIR,SACRAMENTO,95828,CA,4,3,2491,Residential,2008-05-20,245000,38.459711,-121.384283
207,4631 11TH AVE,SACRAMENTO,95820,CA,2,1,1321,Residential,2008-05-20,161829,38.541965,-121.452132

In [11]:
len(df[df['city'] == 'SACRAMENTO'])

439

#### 4) Create a new dataframe that only contains houses with more than 3 bedrooms (beds)

In [12]:
newdf = df[df['beds'].gt(3)]
newdf.sample(5)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
283,5651 OVERLEAF WAY,SACRAMENTO,95835,CA,4,2,1910,Residential,2008-05-20,300500,38.677454,-121.494791
817,506 BEDFORD CT,ROSEVILLE,95661,CA,4,2,2295,Residential,2008-05-16,360000,38.733985,-121.236766
856,1800 AVONDALE DR,ROSEVILLE,95747,CA,5,3,0,Residential,2008-05-16,600000,38.798448,-121.344054
495,251 CHANGO CIR,SACRAMENTO,95835,CA,4,2,2218,Residential,2008-05-19,311328,38.682370,-121.539147
281,993 MANTON CT,GALT,95632,CA,4,3,2307,Residential,2008-05-20,300000,38.272942,-121.289148

### Level - 2 Questions

#### 5) Which city has the highest average house price, and what is that average price?

In [13]:
df.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768

In [14]:
# Using Method - Chaining Method
(
    df
    .groupby('city')['price']
    .mean()
    .round(2)
    .to_frame('Average House Price')
    .sort_values(by='Average House Price', ascending=False)
    .iloc[:1]
)

             Average House Price
city
GRANITE BAY            678733.33

In [15]:
# Another method
avg_df = df.groupby('city')['price'].mean().round(2)
city = avg_df.idxmax()
value = avg_df.max()

print(f'City : {city}, Avg Price : {value}')

City : GRANITE BAY, Avg Price : 678733.33

#### 6) For each different type of property (Residential, Condo, etc.), find both the minimum price and the maximum price.

In [16]:
df.groupby('type')['price'].agg(['min', 'max'])

                 min     max
type
Condo          40000  360000
Multi-Family  100000  416767
Residential     1551  884790
Unkown        275000  275000

### Level - 3 Questions

#### 7) Find all the properties that are Condos AND have a price greater than $300,000. Return a DataFrame showing only their street, city, and price.

In [17]:
(
    df[ (df['type'] == 'Condo') & (df['price'] > 300000) ]
    [['street', 'city', 'price']]
    .sort_values('price')
)

               street        city   price
814   281 SPYGLASS HL   ROSEVILLE  350000
511  1322 SUTTER WALK  SACRAMENTO  360000

### Level - 4 Questions

#### 8) Create a new column in the dataframe called price_per_sqft. Then, find the top 5 streets with the highest price_per_sqft.

In [18]:
# Using Broad-Casting
df['price_per_sqft'] = (df['price'] / df['sq__ft']).round(2)
df = df[df['sq__ft'] > 0]
df= df.sort_values(by='price_per_sqft', ascending=False)
df.iloc[:5]

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,price_per_sqft
292,5411 10TH AVE,SACRAMENTO,95820,CA,2,1,539,Residential,2008-05-20,334000,38.542727,-121.442449,619.67
334,3935 EL MONTE DR,LOOMIS,95650,CA,4,4,1624,Residential,2008-05-20,839000,38.813337,-121.133348,516.63
853,1165 37TH ST,SACRAMENTO,95816,CA,2,1,1252,Residential,2008-05-16,575000,38.568438,-121.457854,459.27
851,3863 LAS PASAS WAY,SACRAMENTO,95864,CA,3,1,1348,Residential,2008-05-16,545000,38.588936,-121.373606,404.30
543,1500 ORANGE HILL LN,PENRYN,95663,CA,3,2,1320,Residential,2008-05-19,506688,38.862708,-121.162092,383.85

### Level - 5 Questions

#### Question 9

**For each city, we want to find out two things:** <br>
1) What is the total number of transactions (count) that took place? <br>
2) What is the median price_per_sqft for that city? <br>

**Bonus: Sort the final result so that the city with the highest median price_per_sqft is at the very top.**

In [19]:
res = df.groupby('city')['price_per_sqft'].agg(['count', 'median']).round(2)
res.columns = ['Total Transactions', 'Median Price Per Sqft']
res = res.sort_values(by='Median Price Per Sqft', ascending=False) 
res.head()

              Total Transactions  Median Price Per Sqft
city
PENRYN                         1                 383.85
LOOMIS                         2                 369.38
GRANITE BAY                    3                 233.49
PLACERVILLE                    5                 225.73
WALNUT GROVE                   1                 220.03

### Level - 6 Questions

#### 10) Convert the sale_date column into a proper pandas datetime data type. Then, print out df['sale_date'].dtype to confirm it changed.

In [20]:
ndf = pd.read_csv('house_prices.csv')
ndf.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768

In [21]:
ndf['sale_date'].dtype

In [22]:
ndf['sale_date'] = pd.to_datetime(ndf['sale_date'])
ndf.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768

In [23]:
ndf['sale_date'].dtype

dtype('<M8[us]')

#### Question 11: Create a new column called day_of_week that contains the actual name of the day (e.g., Monday, 
#### Tuesday) for each transaction. Then, count how many houses were sold on each day of the week.

In [24]:
ndf['day_of_week'] = ndf['sale_date'].dt.day_name()
ndf.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,day_of_week
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879,Wednesday
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,Wednesday
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839,Wednesday
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146,Wednesday
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768,Wednesday

In [25]:
ndf.groupby('day_of_week').size().to_frame('No. of Transactions')

             No. of Transactions
day_of_week
Friday                       264
Monday                       268
Thursday                     118
Tuesday                      177
Wednesday                    158

#### 12) Which specific date (sale_date) generated the highest total revenue (the sum of all house prices combined), and what was that total amount?

In [26]:
(
    ndf
        .groupby('sale_date')['price']
        .agg('sum')
        .to_frame('Total Revenue')
        .sort_values(by='Total Revenue', ascending=False)
        .iloc[:1]
)

            Total Revenue
sale_date
2008-05-16       70307130

#### Question 13: Group the data by the day of the month (e.g., 1st, 15th, 21st) and calculate the average (mean) price for each day.
*Bonus: Sort the index so it reads chronologically from the earliest day of the month to the latest.*

In [27]:
(
    ndf
        .groupby(ndf['sale_date'].dt.day)
        ['price']
        .agg('mean')
        .round(2)
        .to_frame('Mean Price')
        .sort_index()
)

           Mean Price
sale_date
15          167462.86
16          266314.89
19          206361.19
20          262797.02
21          245218.23

#### Question 14: Group the data by the exact sale_date and find the maximum property price sold on each day. Sort it chronologically by the date.

*Bonus Thought: Look closely at your final result table. Is there one specific day where the maximum price looks wildly out of place compared to the others?*

In [28]:
ndf.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,day_of_week
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879,Wednesday
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,Wednesday
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839,Wednesday
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146,Wednesday
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768,Wednesday

In [29]:
(
    ndf
        .groupby(ndf['sale_date'])
        ['price']
        .agg('max')
        .round(2)
        .to_frame('Max Price')
        .sort_index()
)

# Unusual date -> 2008-05-15

            Max Price
sale_date
2008-05-15     235738
2008-05-16     884790
2008-05-19     760000
2008-05-20     839000
2008-05-21     830000

#### Question 15: Filter the DataFrame to show only the transactions that occurred between May 19, 2008 and May 21, 2008 (inclusive).

*Save this filtered data into a new variable called end_of_may_df, and use .shape to see how many homes were sold during this 3-day window.*

In [30]:
end_of_may_df = ndf[ ndf['sale_date'].ge('2008-05-19') &  ndf['sale_date'].le('2008-05-21')]
end_of_may_df.shape

# 603 homes were sold

(603, 13)

#### Question 16: Group the data by both day_of_week and type. Find the total number of transactions and the average price for each combination.

*Bonus: Round the average price to 2 decimal places.*

In [31]:
(
    ndf.groupby(['day_of_week', 'type'])
    ['price']
    .agg(['count', 'mean'])
    .round(2)
)

                          count       mean
day_of_week type
Friday      Condo             6  178282.33
            Multi-Family      2  190575.00
            Residential     255  268946.22
            Unkown            1  275000.00
Monday      Condo            19  149169.16
            Multi-Family      5  231553.40
            Residential     244  210298.44
Thursday    Condo            10  130712.00
            Multi-Family      1  170000.00
            Residential     107  170873.81
Tuesday     Condo             9  154500.00
            Multi-Family      1  256054.00
            Residential     167  268673.76
Wednesday   Condo            10  150291.00
            Multi-Family      4  238495.00
            Residential     144  251997.15

In [32]:
df

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,price_per_sqft
292,5411 10TH AVE,SACRAMENTO,95820,CA,2,1,539,Residential,2008-05-20,334000,38.542727,-121.442449,619.67
334,3935 EL MONTE DR,LOOMIS,95650,CA,4,4,1624,Residential,2008-05-20,839000,38.813337,-121.133348,516.63
853,1165 37TH ST,SACRAMENTO,95816,CA,2,1,1252,Residential,2008-05-16,575000,38.568438,-121.457854,459.27
851,3863 LAS PASAS WAY,SACRAMENTO,95864,CA,3,1,1348,Residential,2008-05-16,545000,38.588936,-121.373606,404.30
543,1500 ORANGE HILL LN,PENRYN,95663,CA,3,2,1320,Residential,2008-05-19,506688,38.862708,-121.162092,383.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,58.45
335,5840 WALERGA RD,SACRAMENTO,95842,CA,2,1,840,Condo,2008-05-19,40000,38.673678,-121.357471,47.62
867,7401 TOULON LN,SACRAMENTO,95828,CA,4,2,1512,Residential,2008-05-15,56950,38.488628,-121.387759,37.67
603,8208 WOODYARD WAY,CITRUS HEIGHTS,95621,CA,3,2,1166,Residential,2008-05-16,30000,38.715322,-121.314787,25.73
866,14151 INDIO DR,SLOUGHHOUSE,95683,CA,3,4,5822,Residential,2008-05-16,2000,38.490447,-121.129337,0.34

In [33]:
ndf

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude,day_of_week
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879,Wednesday
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,Wednesday
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839,Wednesday
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146,Wednesday
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,2008-05-15,232425,38.457679,-121.359620,Thursday
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,2008-05-15,234000,38.499893,-121.458890,Thursday
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,2008-05-15,235000,38.708824,-121.256803,Thursday
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,2008-05-15,235301,38.417000,-121.397424,Thursday
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,2008-05-15,235738,38.655245,-121.075915,Thursday