In [1]:
import pandas as pd
df = pd.read_csv('datasets/uni.csv')
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012

In [2]:
print(f'Dataset has {df.shape[0]} rows and {df.shape[1]} cols')

Dataset has 2200 rows and 14 cols

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   world_rank            2200 non-null   int64
 1   institution           2200 non-null   str
 2   country               2200 non-null   str
 3   national_rank         2200 non-null   int64
 4   quality_of_education  2200 non-null   int64
 5   alumni_employment     2200 non-null   int64
 6   quality_of_faculty    2200 non-null   int64
 7   publications          2200 non-null   int64
 8   influence             2200 non-null   int64
 9   citations             2200 non-null   int64
 10  broad_impact          2000 non-null   float64
 11  patents               2200 non-null   int64
 12  score                 2200 non-null   float64
 13  year                  2200 non-null   int64
dtypes: float64(2), int64(10), str(2)
memory usage: 240.8 KB

In [4]:
df.nunique()

world_rank              1000
institution             1024
country                   59
national_rank            229
quality_of_education     367
alumni_employment        565
quality_of_faculty       199
publications             987
influence                944
citations                135
broad_impact             343
patents                  738
score                    764
year                       4
dtype: int64

In [5]:
df.describe().round(2).loc[['min', 'max', 'mean']]

,world_rank,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
min,1.00,1.00,1.0,1.00,1.00,1.00,1.0,1.00,1.0,1.00,43.36,2012.00
max,1000.00,229.00,367.0,567.00,218.00,1000.00,991.0,812.00,1000.0,871.00,100.00,2015.00
mean,459.59,40.28,275.1,357.12,178.89,459.91,459.8,413.42,496.7,433.35,47.80,2014.32

In [7]:
from sklearn.preprocessing import MinMaxScaler

# 1. Initialize scaler with feature_range=(1, 100)
scaler = MinMaxScaler(feature_range=(1, 100))

# 2. Fit and transform the column
df['quality_of_education'] = scaler.fit_transform(df[['quality_of_education']])
df['alumni_employment'] = scaler.fit_transform(df[['alumni_employment']])
df['quality_of_faculty'] = scaler.fit_transform(df[['quality_of_faculty']])
df['broad_impact'] = scaler.fit_transform(df[['broad_impact']])

In [8]:
df.describe().round(2).loc[['min', 'max', 'mean']]

,world_rank,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
min,1.00,1.00,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.00,43.36,2012.00
max,1000.00,229.00,100.00,100.00,100.00,1000.00,991.0,812.00,100.00,871.00,100.00,2015.00
mean,459.59,40.28,75.14,63.29,82.16,459.91,459.8,413.42,50.12,433.35,47.80,2014.32