In [2]:
# Grouping the multi-indexed df
import pandas as pd
s = pd.Series({'ckm' : 'coffee', 'blr' : 'tech', 'mys' : 'kings'})
df = s.to_frame('famous')
df['temp'] = ['cold', 'hot', 'avg']
df

     famous  temp
ckm  coffee  cold
blr    tech   hot
mys   kings   avg

In [3]:
# Add a new tuple using .loc[]
df.loc['has'] = ['malls', 'avg']
df.loc['dvg'] = ['peda', 'hot']
df

     famous  temp
ckm  coffee  cold
blr    tech   hot
mys   kings   avg
has   malls   avg
dvg    peda   hot

In [4]:
df = df.reset_index()
df = df.sort_values(by='temp')
df = df.set_index(['temp', 'index'])
df

            famous
temp index
avg  mys     kings
     has     malls
cold ckm    coffee
hot  blr      tech
     dvg      peda

In [5]:
for group, frame in df.groupby(level = [0,1]):
    print(group)

('avg', 'has')
('avg', 'mys')
('cold', 'ckm')
('hot', 'blr')
('hot', 'dvg')

In [6]:
for group, frame in df.groupby(level = (0,1)):
    print(group)
    print('\n', frame)
    print('--------------')

('avg', 'has')

            famous
temp index
avg  has    malls
--------------
('avg', 'mys')

            famous
temp index
avg  mys    kings
--------------
('cold', 'ckm')

             famous
temp index
cold ckm    coffee
--------------
('hot', 'blr')

            famous
temp index
hot  blr     tech
--------------
('hot', 'dvg')

            famous
temp index
hot  dvg     peda
--------------

In [7]:
# Groupby using only on temp
for group, frame in df.groupby('temp') :
    print(group)
    print('\n', frame)
    print('--------------')

avg

            famous
temp index
avg  mys    kings
     has    malls
--------------
cold

             famous
temp index
cold ckm    coffee
--------------
hot

            famous
temp index
hot  blr     tech
     dvg     peda
--------------

In [8]:
# Teacher dataframe
import numpy as np

d = {
    'sunitha' : ['hod', 5, 1, True],
    'sathya' : ['asso', 4.5, 2, True],
    'sana ara' : ['assi', 3, 3, True],
    'sonia' : ['assi', 4.5, 4, True],
    'purshi' : ['assi', 3, 3, False],
    'bhavya' : ['assi', 4, 3, False],
    'gowri'  : ['assi', np.nan, 4, True]
}

ndf = pd.DataFrame(d)
ndf = ndf.T
ndf = ndf.reset_index()
ndf.columns = ['name', 'post', 'rating', 'rank', 'like / dislike']
ndf

       name  post rating rank like / dislike
0   sunitha   hod      5    1           True
1    sathya  asso    4.5    2           True
2  sana ara  assi      3    3           True
3     sonia  assi    4.5    4           True
4    purshi  assi      3    3          False
5    bhavya  assi      4    3          False
6     gowri  assi    NaN    4           True

In [9]:
# Sort on the basis of rating
ndf = ndf.dropna()
ndf = ndf.sort_values(by='rating', ascending=False)

for group, frame in ndf.groupby('rating') :
    print(group)

3.0
4.0
4.5
5.0

In [10]:
ndf = ndf.set_index(['rating', 'name'])
ndf

                 post rank like / dislike
rating name
5      sunitha    hod    1           True
4.5    sathya    asso    2           True
       sonia     assi    4           True
4      bhavya    assi    3          False
3      sana ara  assi    3           True
       purshi    assi    3          False

In [11]:
for group, frame in ndf.groupby(['rating', 'name']):
    print(group)

(3.0, 'purshi')
(3.0, 'sana ara')
(4.0, 'bhavya')
(4.5, 'sathya')
(4.5, 'sonia')
(5.0, 'sunitha')

In [12]:
# Advanced Grouping technique using custom function
'''
    5 and above 5 -> Fantastic
    4 and above 4 -> Excellent
    else -> Needs improvement
'''

def comment(item):
    if item[0] >= 5:
        return (item[1],'Fantastic')

    elif item[0] >= 4:
        return (item[1], 'Excellent')

    else:
        return (item[1], 'Needs Improvement')

for group, frame in ndf.groupby(by = comment):
    print(group)

('bhavya', 'Excellent')
('purshi', 'Needs Improvement')
('sana ara', 'Needs Improvement')
('sathya', 'Excellent')
('sonia', 'Excellent')
('sunitha', 'Fantastic')

In [13]:
# 3 Steps of Grouping Data
# Aggregation, Transformation, Filtration

### Aggregation

In [14]:
ndf = ndf.reset_index()
ndf

   rating      name  post rank like / dislike
0     5.0   sunitha   hod    1           True
1     4.5    sathya  asso    2           True
2     4.5     sonia  assi    4           True
3     4.0    bhavya  assi    3          False
4     3.0  sana ara  assi    3           True
5     3.0    purshi  assi    3          False

In [15]:
(
    ndf
        .groupby('post')['rating']
        .agg(['mean', 'count'])
        .round(2)
        .set_axis(['Average Rating to each post', 'Number of Employees'], axis='columns')
        .sort_values(by='Average Rating to each post', ascending=False)
)

      Average Rating to each post  Number of Employees
post
hod                          5.00                    1
asso                         4.50                    1
assi                         3.62                    4

### Transformation

In [16]:
ndf

   rating      name  post rank like / dislike
0     5.0   sunitha   hod    1           True
1     4.5    sathya  asso    2           True
2     4.5     sonia  assi    4           True
3     4.0    bhavya  assi    3          False
4     3.0  sana ara  assi    3           True
5     3.0    purshi  assi    3          False

In [17]:
ndf

   rating      name  post rank like / dislike
0     5.0   sunitha   hod    1           True
1     4.5    sathya  asso    2           True
2     4.5     sonia  assi    4           True
3     4.0    bhavya  assi    3          False
4     3.0  sana ara  assi    3           True
5     3.0    purshi  assi    3          False