In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('datasets/cwurData.csv')
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012

In [4]:
def assign(rank):
    if rank in range(1,101):
        return "First Tier Top University"

    elif rank in range(101, 201):
        return "Second Tier Top University"

    elif rank in range(201, 301):
        return "Third Tier Top University"

    else:
        return "Other Top University"

df['Rank_Level'] = df['world_rank'].apply(assign)

df.sample(10)

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year,Rank_Level
553,354,Xiamen University,China,11,355,100,210,371,507,609,472.0,307,45.80,2014,Other Top University
933,734,Mie University,Japan,50,355,478,210,805,834,609,675.0,338,44.60,2014,Other Top University
716,517,University of Sherbrooke,Canada,21,355,478,210,446,437,406,415.0,637,45.05,2014,Other Top University
2036,837,Boğaziçi University,Turkey,7,367,519,218,843,766,511,781.0,824,44.19,2015,Other Top University
314,115,University of Queensland,Australia,3,265,295,134,75,96,125,102.0,78,50.37,2014,Second Tier Top University
1200,1,Harvard University,USA,1,1,1,1,1,1,1,1.0,3,100.00,2015,First Tier Top University
1203,4,University of Cambridge,United Kingdom,1,2,10,5,11,6,12,13.0,48,96.81,2015,First Tier Top University
876,677,"University of Nevada, Las Vegas",USA,195,355,412,210,619,457,800,628.0,737,44.67,2014,Other Top University
1482,283,University of Bergen,Norway,3,367,567,218,229,201,212,227.0,871,46.18,2015,Third Tier Top University
1192,993,Iran University of Science and Technology,Iran,8,355,478,210,822,987,493,989.0,737,44.25,2014,Other Top University

## Independent Exploration of the Dataset

In [5]:
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year,Rank_Level
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012,First Tier Top University
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012,First Tier Top University
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012,First Tier Top University
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012,First Tier Top University
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012,First Tier Top University

In [6]:
df.dtypes

world_rank                int64
institution                 str
country                     str
national_rank             int64
quality_of_education      int64
alumni_employment         int64
quality_of_faculty        int64
publications              int64
influence                 int64
citations                 int64
broad_impact            float64
patents                   int64
score                   float64
year                      int64
Rank_Level                  str
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   world_rank            2200 non-null   int64
 1   institution           2200 non-null   str
 2   country               2200 non-null   str
 3   national_rank         2200 non-null   int64
 4   quality_of_education  2200 non-null   int64
 5   alumni_employment     2200 non-null   int64
 6   quality_of_faculty    2200 non-null   int64
 7   publications          2200 non-null   int64
 8   influence             2200 non-null   int64
 9   citations             2200 non-null   int64
 10  broad_impact          2000 non-null   float64
 11  patents               2200 non-null   int64
 12  score                 2200 non-null   float64
 13  year                  2200 non-null   int64
 14  Rank_Level            2200 non-null   str
dtypes: float64(2), int64(10), str(3)
memory usage: 257.9 KB

In [10]:
df.describe().round(2).loc[['min', 'max', 'mean']]

,world_rank,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
min,1.00,1.00,1.0,1.00,1.00,1.00,1.0,1.00,1.0,1.00,43.36,2012.00
max,1000.00,229.00,367.0,567.00,218.00,1000.00,991.0,812.00,1000.0,871.00,100.00,2015.00
mean,459.59,40.28,275.1,357.12,178.89,459.91,459.8,413.42,496.7,433.35,47.80,2014.32

## Pivot Table

In [12]:
# Compare rank level versus country of the universities in terms of overall score

# Values -> Score, Index -> Country, Columns -> Rank levels

df.pivot_table(values='score', index='country', columns='Rank_Level', aggfunc='mean').head()

Rank_Level,First Tier Top University,Other Top University,Second Tier Top University,Third Tier Top University
country,,,,
Argentina,NaN,44.672857,NaN,NaN
Australia,47.9425,44.645750,49.2425,47.285000
Austria,NaN,44.864286,NaN,47.066667
Belgium,51.8750,45.081000,49.0840,46.746667
Brazil,NaN,44.499706,49.5650,NaN

In [14]:
df.pivot_table(values='score', index='country', columns='Rank_Level', aggfunc=['mean', 'max']).head()

                                mean                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN            44.672857
Australia                    47.9425            44.645750
Austria                          NaN            44.864286
Belgium                      51.8750            45.081000
Brazil                           NaN            44.499706

                                                                 \
Rank_Level Second Tier Top University Third Tier Top University
country
Argentina                         NaN                       NaN
Australia                     49.2425                 47.285000
Austria                           NaN                 47.066667
Belgium                       49.0840                 46.746667
Brazil                        49.5650                       NaN

                                 max                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN                45.66
Australia                      51.61                45.97
Austria                          NaN                46.29
Belgium                        52.03                46.21
Brazil                           NaN                46.08


Rank_Level Second Tier Top University Third Tier Top University
country
Argentina                         NaN                       NaN
Australia                       50.40                     47.47
Austria                           NaN                     47.78
Belgium                         49.73                     47.14
Brazil                          49.82                       NaN

In [15]:
df.pivot_table(values='score', index='country', columns='Rank_Level', aggfunc=['mean', 'max'], margins=True).head()

                                mean                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN            44.672857
Australia                    47.9425            44.645750
Austria                          NaN            44.864286
Belgium                      51.8750            45.081000
Brazil                           NaN            44.499706

                                                                            \
Rank_Level Second Tier Top University Third Tier Top University        All
country
Argentina                         NaN                       NaN  44.672857
Australia                     49.2425                 47.285000  45.825517
Austria                           NaN                 47.066667  45.139583
Belgium                       49.0840                 46.746667  47.011000
Brazil                        49.5650                       NaN  44.781111

                                 max                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN                45.66
Australia                      51.61                45.97
Austria                          NaN                46.29
Belgium                        52.03                46.21
Brazil                           NaN                46.08


Rank_Level Second Tier Top University Third Tier Top University    All
country
Argentina                         NaN                       NaN  45.66
Australia                       50.40                     47.47  51.61
Austria                           NaN                     47.78  47.78
Belgium                         49.73                     47.14  52.03
Brazil                          49.82                       NaN  49.82

In [16]:
ndf = df.pivot_table(values='score', index='country', columns='Rank_Level', aggfunc=['mean', 'max'], margins=True).head()

ndf.index

Index(['Argentina', 'Australia', 'Austria', 'Belgium', 'Brazil'], dtype='str', name='country')

In [17]:
ndf.columns

MultiIndex([('mean',  'First Tier Top University'),
            ('mean',       'Other Top University'),
            ('mean', 'Second Tier Top University'),
            ('mean',  'Third Tier Top University'),
            ('mean',                        'All'),
            ( 'max',  'First Tier Top University'),
            ( 'max',       'Other Top University'),
            ( 'max', 'Second Tier Top University'),
            ( 'max',  'Third Tier Top University'),
            ( 'max',                        'All')],
           names=[None, 'Rank_Level'])

In [18]:
# If we want mean scores of First tier top university, we need to do projection twice
ndf['mean']['First Tier Top University'].head()

country
Argentina        NaN
Australia    47.9425
Austria          NaN
Belgium      51.8750
Brazil           NaN
Name: First Tier Top University, dtype: float64

In [19]:
# If we want country with highest mean scores in first tier category
ndf['mean']['First Tier Top University'].idxmax()

'Belgium'

In [20]:
nndf = ndf['mean']['First Tier Top University']
    
(
    nndf
        .to_frame('mean values')
        .dropna()
        .sort_values(by='mean values', ascending=False)
        .head(1)
    
)

         mean values
country
Belgium       51.875

In [21]:
# Stack and Unstack functions
ndf.head()

                                mean                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN            44.672857
Australia                    47.9425            44.645750
Austria                          NaN            44.864286
Belgium                      51.8750            45.081000
Brazil                           NaN            44.499706

                                                                            \
Rank_Level Second Tier Top University Third Tier Top University        All
country
Argentina                         NaN                       NaN  44.672857
Australia                     49.2425                 47.285000  45.825517
Austria                           NaN                 47.066667  45.139583
Belgium                       49.0840                 46.746667  47.011000
Brazil                        49.5650                       NaN  44.781111

                                 max                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN                45.66
Australia                      51.61                45.97
Austria                          NaN                46.29
Belgium                        52.03                46.21
Brazil                           NaN                46.08


Rank_Level Second Tier Top University Third Tier Top University    All
country
Argentina                         NaN                       NaN  45.66
Australia                       50.40                     47.47  51.61
Austria                           NaN                     47.78  47.78
Belgium                         49.73                     47.14  52.03
Brazil                          49.82                       NaN  49.82

In [22]:
# Lowermost column to Innermost row

ndf = ndf.stack()
ndf.head()

                                           mean    max
country   Rank_Level
Argentina First Tier Top University         NaN    NaN
          Other Top University        44.672857  45.66
          Second Tier Top University        NaN    NaN
          Third Tier Top University         NaN    NaN
          All                         44.672857  45.66

In [23]:
ndf.unstack().head()

                                mean                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN            44.672857
Australia                    47.9425            44.645750
Austria                          NaN            44.864286
Belgium                      51.8750            45.081000
Brazil                           NaN            44.499706

                                                                            \
Rank_Level Second Tier Top University Third Tier Top University        All
country
Argentina                         NaN                       NaN  44.672857
Australia                     49.2425                 47.285000  45.825517
Austria                           NaN                 47.066667  45.139583
Belgium                       49.0840                 46.746667  47.011000
Brazil                        49.5650                       NaN  44.781111

                                 max                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN                45.66
Australia                      51.61                45.97
Austria                          NaN                46.29
Belgium                        52.03                46.21
Brazil                           NaN                46.08


Rank_Level Second Tier Top University Third Tier Top University    All
country
Argentina                         NaN                       NaN  45.66
Australia                       50.40                     47.47  51.61
Austria                           NaN                     47.78  47.78
Belgium                         49.73                     47.14  52.03
Brazil                          49.82                       NaN  49.82

In [24]:
ndf.unstack().unstack().head() # Series

      Rank_Level                 country
mean  First Tier Top University  Argentina        NaN
                                 Australia    47.9425
                                 Austria          NaN
                                 Belgium      51.8750
                                 Brazil           NaN
dtype: float64