## 1) Ratio Scale :
- Units are Equally Spaced <br>
- All mathematical operations such as +, -, *, / are valid <br>
- Contains abscence of a value like 0 <br>
- Ex : Height, Weight <br>

## 2) Interval Scale :
- Units are Equally Spaced <br>
- No abscence of value, No absolute 0 <br>
- Some mathematical operations are invalid like division <br>
- Ex : Temperature, Direction <br>

## 3) Ordinal Scale :
- Order of Units is important <br>
- Not evenly spaced <br>
- Ex : Grades such as A+, A, B etc <br>

## 4) Nominal Scale :
- Just categories of data, no order <br>
- Most observed <br>
- Ex : Teams of a sports team <br>

In [11]:
import pandas as pd
df=pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'],
                index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 
                       'ok', 'ok', 'ok', 'poor', 'poor'],
               columns=["Grades"])
df

          Grades
excellent     A+
excellent      A
excellent     A-
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

In [12]:
df.dtypes

Grades    str
dtype: object

In [13]:
df['Grades'].astype("category")

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D
Name: Grades, dtype: category
Categories (11, str): ['A', 'A+', 'A-', 'B', ..., 'C+', 'C-', 'D', 'D+']

In [14]:
my_categories = pd.CategoricalDtype(categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'], 
                           ordered=True)

# then we can just pass this to the astype() function
grades=df["Grades"].astype(my_categories)
grades.head()

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
Name: Grades, dtype: category
Categories (11, str): ['D' < 'D+' < 'C-' < 'C' ... 'B+' < 'A-' < 'A' < 'A+']

In [15]:
# Advantages -> Order for boolean masking
df[df['Grades'] > 'C']

     Grades
ok       C+
ok       C-
poor     D+
poor      D

In [16]:
grades[grades > 'C']

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
good         B-
ok           C+
Name: Grades, dtype: category
Categories (11, str): ['D' < 'D+' < 'C-' < 'C' ... 'B+' < 'A-' < 'A' < 'A+']

In [17]:
# Variables with boolean values are typically called as dummy variables
# Built-in function -> get_dummies
# Cut function to make data categorical

grades = grades.to_frame('Values')
grades

          Values
excellent     A+
excellent      A
excellent     A-
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D